### ISSUE TITLE
When trying to connect to a server with just you mod on server and client

### ISSUE THREAD

**Issue by Dslacky** [Theray070696/Tier_System_Mod#3]
Server side log

[03:36:36] [Netty IO #2/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An established connection was aborted by the software in your host machine
    at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[?:1.8.0_40]
    at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[?:1.8.0_40]
    at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[?:1.8.0_40]
    at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_40]
    at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_40]
    at io.netty.buffer.UnpooledUnsafeDirectByteBuf.getBytes(UnpooledUnsafeDirectByteBuf.java:408) ~[UnpooledUnsafeDirectByteBuf.class:?]
    at io.netty.buffer.UnpooledUnsafeDirectByteBuf.readBytes(UnpooledUnsafeDirectByteBuf.java:414) ~[UnpooledUnsafeDirectByteBuf.class:?]
    at io.netty.channel.socket.nio.NioSocketChannel.doWriteBytes(NioSocketChannel.java:214) ~[NioSocketChannel.class:?]
    at io.netty.channel.nio.AbstractNioByteChannel.doWrite(AbstractNioByteChannel.java:178) ~[AbstractNioByteChannel.class:?]
    at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:231) ~[NioSocketChannel.class:?]
    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:680) ~[AbstractChannel$AbstractUnsafe.class:?]
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:260) ~[AbstractNioChannel$AbstractNioUnsafe.class:?]
    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:649) ~[AbstractChannel$AbstractUnsafe.class:?]
    at io.netty.channel.DefaultChannelPipeline$HeadHandler.flush(DefaultChannelPipeline.java:1038) ~[DefaultChannelPipeline$HeadHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:674) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:655) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[ChannelOutboundHandlerAdapter.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:674) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:655) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[ChannelOutboundHandlerAdapter.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:674) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:655) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[ChannelOutboundHandlerAdapter.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:674) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:655) ~[DefaultChannelHandlerContext.class:?]
    at cpw.mods.fml.common.network.handshake.NetworkDispatcher.flush(NetworkDispatcher.java:447) ~[NetworkDispatcher.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:674) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:700) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
    at net.minecraft.network.NetworkManager$1.run(NetworkManager.java:174) [ek.class:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [SingleThreadEventExecutor.class:?]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348) [NioEventLoop.class:?]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_40]
[03:36:36] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: DSlacky lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[03:36:36] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: DSlacky left the game

Client Side log

[03:35:42] [Client thread/INFO]: Connecting to localhost, 25565
[03:35:44] [Netty Client IO #1/INFO] [FML]: Server protocol version 2
[03:35:44] [Netty Client IO #1/INFO] [FML]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S40PacketDisconnect
[03:36:31] [Netty Client IO #2/INFO] [FML]: Attempting connection with missing mods [] at SERVER
[03:36:32] [Client thread/INFO]: Connecting to localhost, 25565
[03:36:35] [Netty Client IO #3/INFO] [FML]: Server protocol version 2
[03:36:35] [Netty Client IO #3/INFO] [FML]: Attempting connection with missing mods [] at SERVER
[03:36:35] [Netty Client IO #3/INFO] [FML]: Injecting existing block and item data into this client instance
[03:36:35] [Netty Client IO #3/INFO] [FML]: Applying holder lookups
[03:36:35] [Netty Client IO #3/INFO] [FML]: Holder lookups applied
[03:36:35] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
[03:36:35] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel tiersystem
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.IndexOutOfBoundsException
    at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:439) ~[EmptyByteBuf.class:?]
    at cpw.mods.fml.common.network.ByteBufUtils.readVarInt(ByteBufUtils.java:46) ~[ByteBufUtils.class:?]
    at cpw.mods.fml.common.network.ByteBufUtils.readUTF8String(ByteBufUtils.java:118) ~[ByteBufUtils.class:?]
    at io.github.Theray070696.tiersystem.network.packet.PacketSyncItems.decodeInto(PacketSyncItems.java:74) ~[PacketSyncItems.class:?]
    at io.github.Theray070696.tiersystem.network.PacketPipeline.decode(PacketPipeline.java:105) ~[PacketPipeline.class:?]
    at io.github.Theray070696.tiersystem.network.PacketPipeline.decode(PacketPipeline.java:35) ~[PacketPipeline.class:?]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 18 more
[03:36:36] [Client thread/INFO] [FML]: Applying holder lookups
[03:36:36] [Client thread/INFO] [FML]: Holder lookups applied

**Comment by Dslacky** [comment]
Just Tryed V4 and can connect to server

**Comment by Dslacky** [comment]
just V5 i cant

**Comment by Theray070696** [comment]
I appreciate all the bugs you're posting. I wouldn't have found these bugs without these reports. Thanks.
